name: 'dbt_booking'
version: '1.0.0'
config-version: 2

profile: 'dbt_booking'

model-paths: ['models']
seed-paths: ['seeds']
snapshot-paths: ['snapshots']
test-paths: ['tests']
macro-paths: ['macros']
analysis-paths: ['analysis']
docs-paths: ['docs']

models:
  dbt_booking:
    raw:
      materialized: table
    stage:
      materialized: view
    mart:
      materialized: table
